### ISSUE TITLE
It doesn't work with Rails 6

### ISSUE THREAD

**Issue by robypez** [Dimkarodinz/activeadmin_ancestry_view#8]
```
class Category < ApplicationRecord
	include Concerns::ActiveadminAncestryView::ModelMethods
	has_ancestry
end
```

When I start the server

```
 1: from /Users/scrivoaroby/Projects/dday_product/app/models/category.rb:1:in `<main>'
/Users/scrivoaroby/Projects/dday_product/app/models/category.rb:2:in `<class:Category>': uninitialized constant Category (call 'Category.connection' to establish a connection)::Concerns (NameError)
Did you mean?  Concurrent
```

**Comment by erotenberg1** [comment]
I have the same problem.

**Comment by ntt1985** [comment]
Hi, same problem for me. Have you solved?
Thank you
